project_name: kangal

builds:
  - id: binary-build
    main: main.go
    binary: bin/kangal
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    ignore:
      - goos: darwin
        goarch: 386

dockers:
  - goos: linux
    goarch: amd64
    binaries:
      - bin/kangal
    image_templates:
      - "hellofreshtech/kangal:latest"
      - "hellofreshtech/kangal:{{.Tag}}"
    dockerfile: Dockerfile
    extra_files:
      - openapi.json

release:
  extra_files:
  - glob: kangal/crd.yaml
