name: "Testing"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: golangci/golangci-lint-action@v1
      with:
        version: v1.30

  integration-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14.6'
    - uses: engineerd/setup-kind@v0.4.0
      with:
        version: "v0.7.0"
    - name: Install Kangal CRD
      run: |
        kubectl apply -f kangal/crd.yaml
    - name: build
      run: |
        go mod vendor
        make build
    - name: Integration Test
      env:
        AWS_ENDPOINT_URL: "localhost:8081"
        AWS_BUCKET_NAME: "kangal-test"
      run: |
        WEB_HTTP_PORT=8080 ./bin/linux.amd64/kangal proxy --kubeconfig="${HOME}/.kube/config" --max-load-tests 1 > /tmp/kangal_proxy.log 2>&1 &
        pid_service=$!
        exit_code=$?
        if [[ ${exit_code} -ne 0 ]]; then
            echo "Failed to run kangal proxy"
            cat /tmp/kangal_proxy.log
            kill ${pid_service}
            exit ${exit_code}
        fi
        sleep 1
        WEB_HTTP_PORT=8888 ./bin/linux.amd64/kangal controller --kubeconfig="${HOME}/.kube/config" > /tmp/kangal_controller.log 2>&1 &
        pid_ctl=$!
        exit_code=$?
        if [[ ${exit_code} -ne 0 ]]; then
            echo "Failed to run kangal controller"
            cat /tmp/kangal_controller.log
            kill ${pid_ctl}
            exit ${exit_code}
        fi
        sleep 1
        KUBECONFIG="${HOME}/.kube/config" make test-integration
