name: "Testing"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: golangci/golangci-lint-action@v1
      with:
        version: v1.30

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.15'
    - uses: engineerd/setup-kind@v0.4.0
    - name: Install Kangal CRD
      run: |
        kubectl apply -f kangal/crd.yaml
    - name: Build
      run: |
        go mod vendor
        make build
    - name: Integration Test
      env:
        AWS_ENDPOINT_URL: "localhost:8081"
        AWS_BUCKET_NAME: "kangal-test"
      run: |
        ./ci/integration-tests.sh
